Task_Management_System/Task_Management_System/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name ='home'),
    path('category/', include('category.urls')),
    path('task/', include('task.urls')),
]

Task_Management_System/category/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='category'
urlpatterns = [
    path('add/', views.add_category, name='add_category')
]

Task_Management_System/task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='task'

urlpatterns = [
    path('add/', views.add_task, name='add_task'),
    path('show/', views.show_task, name='show_task'),
    path('edit/<int:id>', views.edit_task, name='edit_task'),
    path('delete/<int:id>', views.delete_task, name='delete_task'),
]

Task_Management_System/category/models.py
from django.db import models
# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.category_name

Task_Management_System/task/models.py
from django.db import models
from category.models import Category
# Create your models here.

class Task(models.Model):
    task_title = models.CharField(max_length=50)
    task_description = models.TextField()
    category = models.ManyToManyField(Category)
    is_completed = models.BooleanField(default= False)
    task_assign_date = models.DateField()
    
    def __str__(self):
        return self.task_title

Task_Management_System/category/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):
    class Meta: 
        model = Category
        fields = '__all__'

Task_Management_System/task/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta: 
        model = Task
        fields = '__all__'
        widgets = {'task_assign_date': forms.DateInput(attrs={'type': 'date'}),}   

Task_Management_System/Task_Management_System/views.py
from django.shortcuts import render
# Create your views here.

def home(request):
    return render(request,'home.html')

Task_Management_System/category/views.py
from django.shortcuts import render, redirect
from . import forms
# Create your views here.

def add_category(request):
    if request.method == 'POST': 
        category_form = forms.CategoryForm(request.POST) 
        if category_form.is_valid():
            category_form.save()
            return redirect('category:add_category') 
    
    else: 
        category_form = forms.CategoryForm()
    return render(request, 'add_category.html', {'form' : category_form})

Task_Management_System/task/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from task.models import Task
# Create your views here.

def add_task(request):
    if request.method == 'POST': 
        task_form = forms.TaskForm(request.POST)
        if task_form.is_valid():
            task_form.save()
            return redirect('task:add_task')
    
    else: 
        task_form = forms.TaskForm()
    return render(request, 'add_task.html', {'form' : task_form})

def show_task(request):
    t_data = Task.objects.all()
    return render(request,'show_task.html',{'t_data':t_data})

def edit_task(request, id):
    task = models.Task.objects.get(pk=id) 
    task_form = forms.TaskForm(instance=task)
    
    if request.method == 'POST': 
        task_form = forms.TaskForm(request.POST, instance=task) 
        if task_form.is_valid(): 
            task_form.save() 
            return redirect('task:show_task') 
    
    return render(request, 'add_task.html', {'form' : task_form})

def delete_task(request, id):
    task = models.Task.objects.get(pk=id) 
    task.delete()
    return redirect('task:show_task')

Task_Management_System/category/templates/add_category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<form style="width:50% ; margin : auto" method="post">
    <h1>Add Category </h1>
    {% csrf_token %}
    {{form | crispy}}

    <button class="btn btn-warning">Add Category</button>
</form>

{% endblock %}

Task_Management_System/task/templates/add_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}



<form style="width:50% ; margin : auto;" method="post">
    <h1>Add Task </h1>
    {% csrf_token %}
    {{form | crispy}}

    <button class="btn btn-warning">Add Task</button>
</form>


{% endblock %}

Task_Management_System/task/templates/show_task.html
{% extends 'base.html' %}

{% block content %}
<h5 class="text-center mt-3">Total Tasks: {{t_data | length}}</h5>

<div class="container row row-cols-1 row-cols-md-3 g-4 mx-auto mt-3 mb-5">
    {% for tasks in t_data %}
    <div class="col ">
        <div class="card ">
            <div class="card-header fw-bold ">
                Task ID: {{tasks.id}}
            </div>
            <div class="card-body">
                <h5 class="card-title">Task: {{tasks.task_title}}</h5>
                <p class="card-text">{{tasks.task_description}}</p>
                <p class="card-text"><span class="text-danger fw-bold ">Category:</span>
                    {% for cat in tasks.category.all %}
                    <button class="btn btn-secondary  btn-sm m-2" disabled>{{cat.category_name}} </button>
                    {% endfor %}
                </p>
                {% if tasks.is_completed == False %}
                <div>
                    <a href="{% url 'task:edit_task' tasks.id%}" class="btn btn-primary btn-sm ">Edit</a>
                    <a href="{% url 'task:delete_task' tasks.id%}" class="btn btn-danger btn-sm">Delete</a>
                </div>
                {% else %}
                <h4 class="fw-bold ">Completed</h4>
                {% endif %}
            </div>
            <div class="card-footer text-body-secondary">
                Assigned: {{tasks.task_assign_date}}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Task_Management_System/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-expand-lg shadow-sm ">
        <div class=" container">
            <a class="navbar-brand fw-bolder" href="{% url 'home' %}">Task Management System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse gap-2 " id="navbarNavAltMarkup">
                <div class="navbar-nav  ps-lg-3 item-nav">
                    <a class="nav-link " aria-current="page" href="{% url 'category:add_category' %}">Add Category</a>
                    <a class="nav-link " aria-current="page" href="{% url 'task:add_task' %}">Add Task</a>
                    <a class="nav-link " aria-current="page" href="{% url 'task:show_task' %}">Show Tasks</a>

                </div>
            </div>
        </div>
    </nav>
    <section class="container ">
        {% block content %}
        {% endblock %}
    </section>






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

Task_Management_System/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-5">
    <h2>You want to show your tasks??</h2>
    <a class="btn btn-primary" aria-current="page" href="{% url 'task:show_task' %}">Show Tasks</a>
</div>
{% endblock %}